# Generated by Django 5.1 on 2024-08-22 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_teacher_delete_react'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
